### ISSUE TITLE
When calling add user rating to movie 

### ISSUE THREAD

**Issue by BaicoianuIoanSorin** [rycka13/SEP6#156]
<img width="1744" alt="image" src="https://github.com/rycka13/SEP6/assets/71268639/e677045e-c92d-401c-b3c6-73d99c5c2d51">
When calling this API method http://localhost:8080/favorites/add/rating/test123/12978528/12 - it gives 400 bad request.

**Comment by BaicoianuIoanSorin** [comment]
I thought it is because i don't have the favourites table, but it doesn't even get there.\
<img width="1685" alt="image" src="https://github.com/rycka13/SEP6/assets/71268639/fcf7054a-290b-412e-9c09-91a62d4ce9be">

**Comment by rycka13** [comment]
Ratings are from 1 to 10

**Comment by BaicoianuIoanSorin** [comment]
I see now, thanks :)
