### ISSUE TITLE
Additional queries for database

### ISSUE THREAD

**Issue by Titas212** [rycka13/SEP6#59]
Since basic CRUD operations were added to the database, some more complex ones are required.
What we need:
Add Director/Star to a movie.
Get n movies based on x ratings/votes.
Get all Person movies.
Get all People that belong to a movie.
Get movies by year.
Get n movies by year.
Get Person by birth.
Get n most popular movies.
Get person by name.
Get movie by title.
Get n best rated movies.

**Comment by Titas212** [comment]
Please add more queries, that you think we will need.

**Comment by rycka13** [comment]
- [ ] `DirectorsMapper` does not have `getDirectorById `method
- [ ]  `RatingMapper` does not have `getRatingById `method
- [ ]  `StarMapper` does not have `geStarById `method
